### ISSUE TITLE
Account Management Flow Infrastructure

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#144]
This issue lists the necessary infrastructure that the backend will need to have to support a full user login/account flow, as currently documented at https://github.com/leaderboardsgg/leaderboard-site/issues/556.

- Every error response must include a body containing both a unique identifier and a human-readable string describing the error.
- All Base64 encoding of GUIDs must be done in accordance with the standard defined in RFC 7515 Appendix C.

```[tasklist]
### Sub issues
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/148
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/149
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/160
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/153
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/159
```

# Model change

### New Fields
- [x] The user entity must have a non-nullable enumerable field called `Role` that can have one of the following values. The default value is `REGISTERED`.
  - `REGISTERED`
  - `CONFIRMED`
  - `ADMINISTRATOR`
  - `BANNED`

### Deleted fields
The existing `Admin` field on the user object will be deleted and values will be migrated as follows.
- A value of `FALSE` will become a value of `REGISTERED`.
- A value of `TRUE` will become a value of `ADMINISTRATOR`.
