### ISSUE TITLE
Account confirmation

### ISSUE THREAD

**Issue by Dalet** [leaderboardsgg/leaderboard-backend#153]
```[tasklist]
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/147
- [x] Create the account confirmation entity
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/154
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/155
- [ ] Send a confirmation email on user registration (#148)
```

## Model
The account confirmation entity represents an auto-generated token a user can use to confirm their account.

### Fields
Fields are non-nullable unless specified.
| Field       | Type               | Description                                        |
|-------------|--------------------|----------------------------------------------------|
| `Id`        | GUID               | Primary key                                        | 
| `UserId`    | GUID               | Id of the user to confirm (FK)                     | 
| `CreatedAt` | timestamp          | Creation date. Auto-generated on creation.         | 
| `ExpiresAt` | timestamp          | Date until when the confirmation link can be used. | 
| `UsedAt`    | nullable timestamp | Date when the confirmation link was used.          |  

## Related issues
- Functional specs: https://github.com/leaderboardsgg/leaderboard-site/issues/556
- Front-end task: https://github.com/leaderboardsgg/leaderboard-site/issues/564
