### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by Dalet** [leaderboardsgg/leaderboard-backend#159]
```[tasklist]
### Tasks
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/147
- [x] Create the account recovery entity
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/156
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/157
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/158
```

## Model
The account recovery entity represents an auto-generated token a user can use to recover their account.

### Fields
- [x] The account recovery entity must have a non-nullable GUID called `Id` serving as a primary key.
- [x] The account recovery entity must have a non-nullable foreign key called `UserId` referencing the users table.
- [x] The account recovery entity must have a non-nullable auto-generated timestamp called `CreatedAt` that defaults to the current time at the moment of creation.
- [x] The account recovery entity must have a nullable timestamp called `UsedAt` that defaults to NULL.
- [x] The account recovery entity must have a non-nullable timestamp called `ExpiresAt` that defaults to one hour after creation.

**Comment by AV7708614** [comment]
Como puedo hacer un recovery de mi cuenta de Samsung o Gmail si mi número no lo tengo. Creo que mi teléfono esta muy hackeado necesito ayuda y no se a quien Acudir.
