### ISSUE TITLE
Leaderboard Infrastructure

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#238]
```[tasklist]
### Tasks
- [ ] #227 
- [ ] #228 
- [ ] #230 
- [ ] #231 
- [ ] #235 
- [ ] #236 
- [ ] #237
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/223
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/234
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/240
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/245
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/254
```
More to come.
