### ISSUE TITLE
Category Infrastructure

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-backend#258]
Create the endpoints and functionality necessary for actions involving categories.
```[tasklist]
### Tasks
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/222
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/259
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/260
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/261
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/262
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/263
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/264
- [ ] https://github.com/leaderboardsgg/leaderboard-backend/issues/265
```
