### ISSUE TITLE
MVP: Bans

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-backend#31]
🔨🔨🔨

Append each item with the PR that solves it.

## Model/Relationships

- [x] Create the model - refer to [MVP](https://github.com/leaderboardsgg/leaderboard-backend-poc/wiki/MVP-Overview) (#32)
  - Zero or multiple Bans to a User
  - Zero or multiple Bans to a Leaderboard
  - Users: `BanningUser` and `BannedUser` link to a User's ID
  - Leaderboards: `Leaderboard` links to a Leaderboard's ID

## Controller Actions

- [x] GET Ban with ID (https://github.com/leaderboardsgg/leaderboard-backend-poc/pull/53)
- [x] GET all Bans, optionally filtered by either Leaderboard ID or User ID (https://github.com/leaderboardsgg/leaderboard-backend-poc/pull/53)
- [x] POST Bans as admin with: (https://github.com/leaderboardsgg/leaderboard-backend/pull/95)
  - User ID;
  - Reason;
  - Condition: must be admin
  - Condition: Leaderboard ID **must** be `null` i.e. admins can only give site-wide bans
  - Condition: User to be banned **must not** be admin
- [x] POST Bans as mod with: (https://github.com/leaderboardsgg/leaderboard-backend/pull/95)
  - User ID;
  - Reason;
  - Leaderboard ID;
  - Condition: Leaderboard ID **must not** be `null`
  - Condition: User to be banned **must not** be mod **nor** admin
- [ ] Soft DELETE Ban as admin with Ban ID (#101)
- [ ] Soft DELETE Ban as mod with: (#101)
  - Ban ID;
  - Leaderboard ID

## Post-action Behaviours

- [ ] New Ban for User, if mod:
  - Modship for any and all Leaderboards removed; and
  - any and all Runs across all Leaderboards rejected
- [ ] New Ban for User if not mod:
  - any and all Runs for specific Leaderboard rejected

## Other Relevant Issues
(To be filled)

**Comment by TheTedder** [comment]
Bans have been retconned by #144. They're part of our rudimentary role system now.

**Comment by just-ero** [comment]
Please update this issue to reflect the current status.

* deleting bans has been implemented (#101)
* users no longer have modships, which nullifies `Ban for User, if mod`

**Comment by just-ero** [comment]
In fact, do we even have bans anymore? I'm looking through the code right now, and there's not a single mention of the word `ban`. What happened?

**Comment by TheTedder** [comment]
Bans have been heavily simplified for MVP such that an entire controller/DB table for them is no longer necessary. A user whose Role is BANNED is now considered banned.
